# Application properties for Inventory Service
spring.application.name=INVENTORY-SERVICE
spring.cloud.config.name=inventory-service
#Spring profile configurations
spring.profiles.active=dev
# Spring config server configurations
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}
