spring.application.name=CART-ORDER-SERVICE
spring.cloud.config.name=cart-order-service
# Spring profile configurations
spring.profiles.active=dev
# Spring config server configurations
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}