spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  application:
    name: API-GATEWAY

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: READ_ONLY

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

product:
  service:
    id: lb://PRODUCTS-SERVICE
    uri: ${PRODUCT_SERVICE_URI:http://localhost:8081}

cartOrder:
  service:
    id: lb://CART-ORDER-SERVICE
    uri: ${CART_ORDER_SERVICE_URI:http://localhost:8082}