spring:
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 60000
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
              lower-case-service-id: true
  application:
    name: API-GATEWAY

management:
  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    gateway:
      access: READ_ONLY

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}

resilience4j.circuitbreaker:
  configs:
    default:
      sliding-window-size: 10
      permitted-number-of-calls-in-half-open-state: 2
      failure-rate-threshold: 50
      wait-duration-in-open-state: 10000

PRODUCT_SERVICE_ID: lb://PRODUCTS-SERVICE
INVENTORY_SERVICE_ID: lb://INVENTORY-SERVICE
CART_ORDER_SERVICE_ID: lb://CART-ORDER-SERVICE
USER_SERVICE_ID: lb://USER-SERVICE

jwt:
  secret: '${JWT_SECRET:DEv(Nk8U}x(Z#%@*cfdN)IgY$2M/FeiptC}qk7_[>i1cW(Ax&0bI@k!{{;2]?qt>YQ^BOChy^$h<WM^yF]y0Hn}'
