apiVersion: v1
kind: ConfigMap

metadata:
  name: blog-config-map

data:
  SPRING_ACTIVE_PROFILE: prod
  DB_HOST: mysql-service
  DB_PORT: "3306"
  DB_NAME: blogdb
  MYSQL_ROOT_PASSWORD: pranay123
  MYSQL_DATABASE: blogdb
