apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ include "stateful-blog.fullname" . }}-config-map
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}

data:
  SPRING_ACTIVE_PROFILE: {{ .Values.config.springProfilesActive | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
