# This is the specification for the deployment.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stateful-blog.fullname" . }}-deployment
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.blogApp.replicaCount }}
  selector:
    matchLabels:
      app: blogapp

  # Template helps create the pod.
  # This is a specification for the pods creation.
  template:
    metadata:
      labels:
        app: blogapp
    spec:
      containers:
        - name: blogapp-container
          image: {{ .Values.blogApp.image.repository }}:{{ .Values.blogApp.image.tag }}
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stateful-blog.fullname" . }}-config-map
                  key: SPRING_ACTIVE_PROFILE
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stateful-blog.fullname" . }}-config-map
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stateful-blog.fullname" . }}-config-map
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: {{ include "stateful-blog.fullname" . }}-config-map
                  key: DB_NAME
          resources: {{- toYaml .Values.blogApp.resources | nindent 12 }}
