apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stateful-blog.fullname" . }}-secret
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.auth.rootPassword | b64enc | quote }}
