apiVersion: v1
kind: Service
metadata:
  name: {{ include "stateful-blog.fullname" . }}-service
  labels: {{- include "stateful-blog.labels" . | nindent 4 }}

spec:
  type: {{ .Values.blogApp.service.type | quote }}
  selector:
    app: blogapp

  ports:
    - protocol: TCP
      port: {{ .Values.blogApp.service.port }}
      targetPort: {{ .Values.blogApp.service.targetPort }}
    # ClusterIP is used to access within the cluster.
  #type: ClusterIP
  type: LoadBalancer
