spring.application.name=PAYMENT-SERVICE
spring.cloud.config.name=payment-service
# Spring profile configurations
spring.profiles.active=dev
# Spring config server configurations
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}

