spring.application.name=products-service
# Datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/products_db
spring.datasource.username=postgres
spring.datasource.password=Pranay@666
spring.datasource.driver-class-name=org.postgresql.Driver
# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
# HikariCP configuration
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
# Image storage configuration
IMAGEKIT_PRIVATE_KEY=private_+p7aT93FpXiJDMWUZYTAlEfArH4=
IMAGEKIT_PUBLIC_KEY=public_7he7OGZigoRkGc2h1KQg6rjqSHw=
IMAGEKIT_URL_ENDPOINT=https://ik.imagekit.io/ugfc6txa5
IMAGEKIT_FOLDER=/products
# Port configuration
server.port=8081
# Debugging configuration
logging.level.org.springframework=INFO
logging.level.com.pranay.easybuy=DEBUG