spring.application.name=PRODUCTS-SERVICE
spring.cloud.config.name=products-service
# Spring profile configurations
spring.profiles.active=dev
# Spring config server configurations
spring.config.import=configserver:${CONFIG_SERVER_URL:http://localhost:8079}
